
platform :ios, '13.0'

target 'ToDoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoList
    
    pod 'RealmSwift', '=10.0.0-beta.2'
    pod 'SwipeCellKit'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon', :branch => 'swift5'

end
